import os
import sys
sys.path.append('../')
from conf import *

mode = ARGUMENTS.get('mode', 'debug')
if not (mode in ['debug', 'release']):
   print('Error: expected "debug" or "release", found: ' + mode)
   Exit(1)

env = Environment(ENV=os.environ,
                  tools=['default', FCC],
                  F90FLAGS=FFLAGS[mode],
                  LINKFLAGS=LDFLAGS[mode])
                  # FORTRANMODDIR=FORTRANMODDIR)
SConscript('SConscript', exports=['env'])
